plate_data_dirs:
    - 'Plate1'
    - 'Plate2'
    - 'Plate3'

plate_labels:
    - 'labels/plate1_labels.csv'
    - 'labels/plate2_labels.csv'
    - 'labels/plate3_labels.csv'

nthread: 20

analysis_name: 'van_de_rijn'

# Each item is for the corresponding plate
failed_qc1:
    - 'A7,B5,D2'
    - 'D5,D6,F5,F6,G6'
    - 'C7,E6'

failed_qc2:
    - 'D1,C2,E2,H2,H3,A4,H5,A6,G7,E10,H10,B11,G11'
    - 'C2,D2,D3,H4,H5,E8,E10'
    - 'D2,E2,H4,A4,C8,B10,A12'
    - 'B1'

failed_qc3:
    - 'B2,D5,F9,A1,C4,E8,G11'
    - 'F3,E6,C8,A12,E4,D7,B11'
    - 'B7,H2,G3,D5,A6,B9,A10'
    - 'A1'
 
# Regex columns based on these strings
# NOTE: underscores get substituted to spaces inside the R script
cancer_types:
    - 'LMS'
    - 'LM'
    - 'GIST'
    - 'DTF'
    - 'DTF_het'