plate_data_dirs:
    - 'Plate1'
    - 'Plate2'
    - 'Plate3'

plate_labels:
    - 'labels/plate1_labels.csv'
    - 'labels/plate2_labels.csv'
    - 'labels/plate3_labels.csv'

nthread: 14

analysis_name: 'stanford_LMS'

# Each item is for the corresponding plate
failed_qc1:
    - 'B5,C2,D2,F6,H1,H3'
    - 'D5,D6,F5,F6,G6,H5'
    - 'C7,C8,D5'

failed_qc2:
    - 'B1,C8'
    - 'A6,E7,E11'

failed_qc3:
    - 'B2,D5,F9,A1,C4,E8,G11'
    - 'F3,E6,C8,A12,E4,D7,B11'
    - 'B7,H2,G3,D5,A6,B9,A10'
    - 'A1'
 
# Regex columns based on these strings
# NOTE: underscores get substituted to spaces inside the R script
cancer_types:
    - 'LMS'
    - 'LM'
    - 'GIST'
    - 'DTF'
    - 'DTF_het'