plate_data_dirs:
    - 'Plate1'
    - 'Plate2'
    - 'Plate3'

plate_labels:
    - 'labels/plate1_labels.csv'
    - 'labels/plate2_labels.csv'
    - 'labels/plate3_labels.csv'

nthread: 20

analysis_name: 'van_de_rijn'

# Set the p-value cut-off for calling CpG probes as detected
detection_pvalue: 0.05

# Set the minimum bisulphite conversion rate for a sample to pass QC
bisulphite_conversion_rate: 90

# Specify iterative steps of manual QC, where the step name is first followed by a colon, 
#   then a comma separated list of wells for plate 1, then a colon, a comma separated list of wells
#   for plate 2, etc.
manual_qc_steps:
    - 'logMU9:H3'
    - 'noJurkat:B3,D5,F9,A1,C4,E8,G11;F3,E6,C8,A12,E4,D7,B11;B7;A1'
    - 'noReplicates:B1,C8,F6;A6,E7,E11'
    - 'DTFunique:E3,E4,E6,D7,B9,A10;E1,F2,G3,B4,F4,B5,A8,A9,D9,E9,C10,D10,H10,C11,H11,B12,D12,H12;G1,F4,G4,H4,A5,A7,E7,F7,A8,E8,B12'

preprocess_methods: 'Funnorm,Illumina,Noob,SWAN'

selected_preprocess_method: 'Illumina'

# Same as previous manual QC steps, except on the preprocessed/normalized methylSet
manual_qc2_steps:
    - 'threePeaks:H4,E9,A12,F12;G10;H12;G2'
    - 'aucRatioGt1.75:H1,G3,F6,F7,G8,G9,F10,F11;D1,C3,G7;D1,A2,A9;E1,A2'

selected_qc2_step: 'threePeaks'

# Regex columns based on these strings
# NOTE: underscores get substituted to spaces inside the R script
cancer_types:
    - 'LMS'
    - 'LM'
    - 'GIST'
    - 'DTF'
    - 'DTF_het'